spring.application.name=backend-kpis-management

spring.jackson.time-zone=America/Bogota

# Configuración de la base de datos
#spring.datasource.url=jdbc:mysql://kpismanagement-dbkpisproduccion-ihnc7q:3306/mysql?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#spring.datasource.username=mysql
#spring.datasource.password=13051999aA@
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuración de la base de datos local
spring.datasource.url=jdbc:mysql://localhost:3306/kpis_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=161118
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración del servidor
#server.port=${PORT:8080}

# Propiedades para JWT
jwt.secret=U3ByaW5nU2VjdXJpdHlKd3RLZXlTdXBlclNlY3JldDEyMzQ1Ng==
jwt.expirationMs=3600000 
# 1 hora en milisegundos

app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.email=${APP_ADMIN_EMAIL:admin@gmail.com}
app.admin.password=${APP_ADMIN_PASSWORD:admin123}
app.version=3.0.0


